CREATE TABLE `reference_images` (
  `id` varchar(36) NOT NULL,
  `tenant_id` varchar(64) NOT NULL,
  `project_id` varchar(64) NOT NULL,
  `conversation_id` varchar(36) NULL,
  `message_id` varchar(100) NULL,
  `workflow_id` varchar(36) NULL,
  `object_key` varchar(512) NOT NULL,
  `file_name` varchar(255) NOT NULL,
  `declared_mime_type` varchar(100) NOT NULL,
  `mime_type` varchar(100) NULL,
  `declared_size_bytes` int NOT NULL,
  `size_bytes` int NULL,
  `width` int NULL,
  `height` int NULL,
  `sha256` varchar(64) NULL,
  `status` varchar(32) NOT NULL,
  `declaration_json` json NULL,
  `analysis_json` json NULL,
  `error_code` varchar(64) NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `reference_images_object_key_uq` (`object_key`),
  KEY `reference_images_scope_status_idx` (`tenant_id`, `project_id`, `status`),
  KEY `reference_images_message_idx` (`conversation_id`, `message_id`),
  KEY `reference_images_workflow_idx` (`workflow_id`)
);
