export const VIDEO_WORKFLOW_REPOSITORY = Symbol("VIDEO_WORKFLOW_REPOSITORY");
export const AGENT_EXTENSION_REPOSITORY = Symbol("AGENT_EXTENSION_REPOSITORY");
export const VIDEO_OBJECT_STORAGE = Symbol("VIDEO_OBJECT_STORAGE");
export const MASTRA_RUNTIME = Symbol("MASTRA_RUNTIME");
export const CONVERSATION_REPOSITORY = Symbol("CONVERSATION_REPOSITORY");
